/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rentcar.vistas;

/**
 *
 * @author User
 */
public class MenuAdmin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuAdmin.class.getName());

    /**
     * Creates new form MenuAdmin
     */
    private int nivel;

    public MenuAdmin(int nivel) {
        initComponents();
        this.nivel = nivel;
        aplicarPermisos();
    }

    private void aplicarPermisos() {

        if (nivel == 1) { // usuario normal

            itemUsuarios.setEnabled(false);
            itemGamas.setEnabled(false);
            itemVehiculos.setEnabled(false);
            itemOfertas.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMantenimientos = new javax.swing.JMenu();
        itemUsuarios = new javax.swing.JMenuItem();
        itemGamas = new javax.swing.JMenuItem();
        itemVehiculos = new javax.swing.JMenuItem();
        itemClientes = new javax.swing.JMenuItem();
        itemOfertas = new javax.swing.JMenuItem();
        menuMovimiento = new javax.swing.JMenu();
        itemReservas = new javax.swing.JMenuItem();
        itemRecepcion = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        itemConClientes = new javax.swing.JMenuItem();
        itemConClientesId = new javax.swing.JMenuItem();
        itemConClientesRango = new javax.swing.JMenuItem();
        itemConVehiculos = new javax.swing.JMenuItem();
        itemConVehMatricula = new javax.swing.JMenuItem();
        itemConVehDisponibles = new javax.swing.JMenuItem();
        itemConVehRentados = new javax.swing.JMenuItem();
        itemConVehMarca = new javax.swing.JMenuItem();
        itemConVehGama = new javax.swing.JMenuItem();
        itemConOfertas = new javax.swing.JMenuItem();
        itemConVehPrecio = new javax.swing.JMenuItem();
        itemConReservaFecha = new javax.swing.JMenuItem();
        itemConReservaDias = new javax.swing.JMenuItem();
        itemConRecepcionFecha = new javax.swing.JMenuItem();
        Sesion = new javax.swing.JMenu();
        itemCerrarSesion = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuMantenimientos.setText("Mantenimientos");

        itemUsuarios.setText("Usuarios");
        itemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUsuariosActionPerformed(evt);
            }
        });
        menuMantenimientos.add(itemUsuarios);

        itemGamas.setText("Gamas");
        itemGamas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGamasActionPerformed(evt);
            }
        });
        menuMantenimientos.add(itemGamas);

        itemVehiculos.setText("Vehiculos");
        itemVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVehiculosActionPerformed(evt);
            }
        });
        menuMantenimientos.add(itemVehiculos);

        itemClientes.setText("Clientes");
        itemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemClientesActionPerformed(evt);
            }
        });
        menuMantenimientos.add(itemClientes);

        itemOfertas.setText("Ofertas");
        itemOfertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOfertasActionPerformed(evt);
            }
        });
        menuMantenimientos.add(itemOfertas);

        jMenuBar1.add(menuMantenimientos);

        menuMovimiento.setText("Movimientos");

        itemReservas.setText("Reservas Clientes");
        menuMovimiento.add(itemReservas);

        itemRecepcion.setText("Recepcion Vehiculos");
        menuMovimiento.add(itemRecepcion);

        jMenuBar1.add(menuMovimiento);

        menuConsultas.setText("Consultas");

        itemConClientes.setText("Clientes");
        menuConsultas.add(itemConClientes);

        itemConClientesId.setText("Clientes por ID");
        menuConsultas.add(itemConClientesId);

        itemConClientesRango.setText("Clientes por rango ID");
        menuConsultas.add(itemConClientesRango);

        itemConVehiculos.setText("Vehiculos");
        menuConsultas.add(itemConVehiculos);

        itemConVehMatricula.setText("Vehiculo por matricula");
        menuConsultas.add(itemConVehMatricula);

        itemConVehDisponibles.setText("Vehiculos disponibles");
        menuConsultas.add(itemConVehDisponibles);

        itemConVehRentados.setText("Vehiculos Rentados");
        menuConsultas.add(itemConVehRentados);

        itemConVehMarca.setText("Vehiculos por marca");
        menuConsultas.add(itemConVehMarca);

        itemConVehGama.setText("Vehiculos por gama");
        menuConsultas.add(itemConVehGama);

        itemConOfertas.setText("Ofertas");
        menuConsultas.add(itemConOfertas);

        itemConVehPrecio.setText("Vehiculos por precio");
        menuConsultas.add(itemConVehPrecio);

        itemConReservaFecha.setText("Reservas por fecha");
        menuConsultas.add(itemConReservaFecha);

        itemConReservaDias.setText("Reservas por dias");
        menuConsultas.add(itemConReservaDias);

        itemConRecepcionFecha.setText("Recepcion por fecha");
        menuConsultas.add(itemConRecepcionFecha);

        jMenuBar1.add(menuConsultas);

        Sesion.setText("Sesion");

        itemCerrarSesion.setText("Cerrar Sesion");
        itemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCerrarSesionActionPerformed(evt);
            }
        });
        Sesion.add(itemCerrarSesion);

        jMenuBar1.add(Sesion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUsuariosActionPerformed
        // TODO add your handling code here:
        RegistroUsuario ru = new RegistroUsuario(this);
        ru.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_itemUsuariosActionPerformed

    private void itemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCerrarSesionActionPerformed
        // TODO add your handling code here:

        this.dispose(); // cierra el menú

        new Login().setVisible(true); // vuelve al login

    }//GEN-LAST:event_itemCerrarSesionActionPerformed

    private void itemGamasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGamasActionPerformed
        // TODO add your handling code here:
        RegistroGama rg = new RegistroGama(this);
        rg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemGamasActionPerformed

    private void itemVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVehiculosActionPerformed
        // TODO add your handling code here:
        RegistroVehiculo rv = new RegistroVehiculo(this);
        rv.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemVehiculosActionPerformed

    private void itemOfertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOfertasActionPerformed
        // TODO add your handling code here:
        
        itemOfertas.addActionListener(e -> {
    new RegistroOferta(this).setVisible(true);
    this.setVisible(false);
});
    }//GEN-LAST:event_itemOfertasActionPerformed

    private void itemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemClientesActionPerformed
        // TODO add your handling code here:
        itemClientes.addActionListener(e -> {
    new RegistroCliente(this).setVisible(true);
    this.setVisible(false);
});
    }//GEN-LAST:event_itemClientesActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Sesion;
    private javax.swing.JMenuItem itemCerrarSesion;
    private javax.swing.JMenuItem itemClientes;
    private javax.swing.JMenuItem itemConClientes;
    private javax.swing.JMenuItem itemConClientesId;
    private javax.swing.JMenuItem itemConClientesRango;
    private javax.swing.JMenuItem itemConOfertas;
    private javax.swing.JMenuItem itemConRecepcionFecha;
    private javax.swing.JMenuItem itemConReservaDias;
    private javax.swing.JMenuItem itemConReservaFecha;
    private javax.swing.JMenuItem itemConVehDisponibles;
    private javax.swing.JMenuItem itemConVehGama;
    private javax.swing.JMenuItem itemConVehMarca;
    private javax.swing.JMenuItem itemConVehMatricula;
    private javax.swing.JMenuItem itemConVehPrecio;
    private javax.swing.JMenuItem itemConVehRentados;
    private javax.swing.JMenuItem itemConVehiculos;
    private javax.swing.JMenuItem itemGamas;
    private javax.swing.JMenuItem itemOfertas;
    private javax.swing.JMenuItem itemRecepcion;
    private javax.swing.JMenuItem itemReservas;
    private javax.swing.JMenuItem itemUsuarios;
    private javax.swing.JMenuItem itemVehiculos;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenu menuMantenimientos;
    private javax.swing.JMenu menuMovimiento;
    // End of variables declaration//GEN-END:variables
}
